FROM python:3.11-slim AS builder

WORKDIR /app

RUN pip install --upgrade pip

COPY pyproject.toml README.md ./
COPY src/ ./src/

RUN pip install --no-cache-dir ".[test]"

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

COPY src/ ./src/
COPY tests/ ./tests/

CMD ["pytest", "-v"]